export const ADD_VISITED_VIEW = "ADD_VISITED_VIEW"
export const DEL_VISITED_VIEW = "DEL_VISITED_VIEW"
export const DEL_ORTHERS_VIEW = "DEL_ORTHERS_VIEW"
export const DEL_ALL_VIEW = "DEL_ALL_VIEW"

export const ADD_ROUTER_LIST = "ADD_ROUTER_LIST"
export const ADD_ROUTER_ITEM = "ADD_ROUTER_ITEM"
export const UPDATE_ROLE = "UPDATE_ROLE"
